/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedNfeRouteImport } from './routes/_authenticated/nfe'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated/comissoes'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNfeRoute = AuthenticatedNfeRouteImport.update({
  id: '/nfe',
  path: '/nfe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/nfe': typeof AuthenticatedNfeRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/nfe': typeof AuthenticatedNfeRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/cadastros'
    | '/comissoes'
    | '/dashboard'
    | '/nfe'
    | '/pedidos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/trocar-senha'
    | '/cadastros'
    | '/comissoes'
    | '/dashboard'
    | '/nfe'
    | '/pedidos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/trocar-senha'
    | '/_authenticated/cadastros'
    | '/_authenticated/comissoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/nfe'
    | '/_authenticated/pedidos'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nfe': {
      id: '/_authenticated/nfe'
      path: '/nfe'
      fullPath: '/nfe'
      preLoaderRoute: typeof AuthenticatedNfeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNfeRoute: typeof AuthenticatedNfeRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNfeRoute: AuthenticatedNfeRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
